from typing import List
from pydantic import Json
import datetime

users: List[Json] = [
    {
        "full_name": "Bal Krishna Bal",
        "email": "bal.bal@gmail.com",
        "is_active": True,
        "user_type": 2,
        "address": "Dhulikhel, Kavre",
        "group_id": None,
        "contact_number": "+977-9849721522",
        "teacher_group": [],
        "dob": datetime.datetime(1970, 12, 12),
        "join_year": 1990,
        "password": "bal.bal",
    },
    {
        "full_name": "Yugesh Upadhyaya Luitel",
        "email": "yugu.luitel@gmail.com",
        "is_active": True,
        "user_type": 4,
        "address": "Bafal, Kathmandu",
        "group_id": 1,
        "contact_number": "+977-9861589390",
        "teacher_group": [],
        "dob": datetime.datetime(2001, 6, 13),
        "join_year": 2019,
        "password": "yugu.luitel",
    },
    {
        "full_name": "Arpan Koirala",
        "email": "arpan.koirala@gmail.com",
        "is_active": True,
        "user_type": 4,
        "address": "Rani Mahal, Palpa",
        "group_id": 1,
        "contact_number": "+977-9821694321",
        "teacher_group": [],
        "dob": datetime.datetime(2000, 2, 26),
        "join_year": 2018,
        "password": "arpan.koirala",
    },
    {
        "full_name": "Rushab Humagain",
        "email": "rushab.humagain@gmail.com",
        "is_active": True,
        "user_type": 4,
        "address": "Banepa, Kavre",
        "group_id": 3,
        "contact_number": "+977-9854632157",
        "teacher_group": [],
        "dob": datetime.datetime(2002, 11, 30),
        "join_year": 2020,
        "password": "rushab.humagain",
    },
    {
        "full_name": "Abhijeet Poudel",
        "email": "abhijeet.poudel@gmail.com",
        "is_active": True,
        "user_type": 4,
        "address": "Pokhara Airport Side, Pokhara",
        "group_id": 4,
        "contact_number": "+977-9852891559",
        "teacher_group": [],
        "dob": datetime.datetime(2000, 12, 10),
        "join_year": 2018,
        "password": "abhijeet.poudel",
    },
    {
        "full_name": "Aatish Shrestha",
        "email": "aatish.shrestha@gmail.com",
        "is_active": True,
        "user_type": 4,
        "address": "Koteshowr, Kathmandu",
        "group_id": 5,
        "contact_number": "+977-9845427715",
        "teacher_group": [],
        "dob": datetime.datetime(1998, 4, 12),
        "join_year": 2017,
        "password": "aatish.shrestha",
    },
    {
        "full_name": "Suraj Chapagain ",
        "email": "suraj.chapagain@gmail.com",
        "is_active": True,
        "user_type": 3,
        "address": "Lake Side, Pokhara",
        "group_id": None,
        "contact_number": "+977-9825852660",
        "teacher_group": [[2, 2], [3, 1]],
        "dob": datetime.datetime(1995, 1, 26),
        "join_year": 2020,
        "password": "suraj.chapagain",
    },
    {
        "full_name": "Manoj Pandey",
        "email": "manoj.pandey@gmail.com",
        "is_active": True,
        "user_type": 3,
        "address": "Jitgadhi, Butwal",
        "group_id": None,
        "contact_number": "+977-9833584635",
        "teacher_group": [[1, 1], [3, 1], [5, 1]],
        "dob": datetime.datetime(1885, 9, 14),
        "join_year": 2000,
        "password": "manoj.pandey",
    },
    {
        "full_name": "Om Nath Acharya",
        "email": "om.acharya@gmail.com",
        "is_active": False,
        "user_type": 3,
        "address": "Dhulikhel, Kavre",
        "group_id": None,
        "contact_number": "+977-9875278464",
        "teacher_group": [[4, 2], [1, 2]],
        "dob": datetime.datetime(1980, 8, 14),
        "join_year": 2005,
        "password": "om.acharya",
    },
    {
        "full_name": "Sikshyalaya",
        "email": "sikshyalaya@gmail.com",
        "is_active": True,
        "user_type": 1,
        "address": "Sikshyalaya",
        "group_id": None,
        "contact_number": "+977-9858630918",
        "teacher_group": [],
        "dob": datetime.datetime(2021, 1, 1),
        "join_year": 2021,
        "password": "sikshyalaya",
    },
]
