"""models updated

Revision ID: 0650daca7648
Revises: ed52481355e8
Create Date: 2021-04-13 09:02:36.688954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0650daca7648"
down_revision = "ed52481355e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
