"""Models Created

Revision ID: 2664a34d3eba
Revises: e0e327c1918d
Create Date: 2021-04-13 08:21:37.533289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2664a34d3eba'
down_revision = 'e0e327c1918d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
