"""Models Update

Revision ID: 26790c46d2ee
Revises: c237f7393087
Create Date: 2021-04-18 07:30:25.329195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26790c46d2ee'
down_revision = 'c237f7393087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'contact_number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'contact_number',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
