"""models updated

Revision ID: 2b9e460b4b83
Revises: eb7068eb174f
Create Date: 2021-04-13 09:01:26.224710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9e460b4b83'
down_revision = 'eb7068eb174f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
