"""empty message

Revision ID: 2cc9ab11555a
Revises: 09e50984e1b8
Create Date: 2021-03-23 08:34:38.657052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc9ab11555a'
down_revision = '09e50984e1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
