"""empty message

Revision ID: 3975b1ac80a3
Revises: 2cc9ab11555a
Create Date: 2021-03-23 08:44:36.030048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3975b1ac80a3'
down_revision = '2cc9ab11555a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
