"""table new

Revision ID: 787b5641333c
Revises: 26790c46d2ee
Create Date: 2021-04-21 18:21:24.957970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787b5641333c'
down_revision = '26790c46d2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpermission_name'), 'userpermission', ['name'], unique=True)
    op.create_table('user_permission_association',
    sa.Column('userpermission_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userpermission_id'], ['userpermission.id'], )
    )
    op.add_column('class_session', sa.Column('duration', sa.Integer(), nullable=True))
    op.alter_column('class_session', 'description',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_constraint('class_session_course_id_fkey', 'class_session', type_='foreignkey')
    op.drop_constraint('class_session_group_id_fkey', 'class_session', type_='foreignkey')
    op.create_foreign_key(None, 'class_session', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_session', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('course_department_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'user_type',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_department_id_fkey', 'course', 'department', ['department_id'], ['id'])
    op.drop_constraint(None, 'class_session', type_='foreignkey')
    op.drop_constraint(None, 'class_session', type_='foreignkey')
    op.create_foreign_key('class_session_group_id_fkey', 'class_session', 'group', ['group_id'], ['id'])
    op.create_foreign_key('class_session_course_id_fkey', 'class_session', 'course', ['course_id'], ['id'])
    op.alter_column('class_session', 'description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('class_session', 'duration')
    op.drop_table('user_permission_association')
    op.drop_index(op.f('ix_userpermission_name'), table_name='userpermission')
    op.drop_table('userpermission')
    # ### end Alembic commands ###
