"""Models Created

Revision ID: 7a6ed04886ad
Revises: 8d030df6fff0
Create Date: 2021-04-13 07:47:37.439718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6ed04886ad'
down_revision = '8d030df6fff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('personalnote_course_id_fkey', 'personalnote', type_='foreignkey')
    op.create_foreign_key(None, 'personalnote', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personalnote', type_='foreignkey')
    op.create_foreign_key('personalnote_course_id_fkey', 'personalnote', 'user', ['course_id'], ['id'])
    op.drop_table('association')
    # ### end Alembic commands ###
