"""Models Created

Revision ID: 88ae051a140c
Revises: aa4c54cbfe21
Create Date: 2021-04-12 16:49:39.501408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ae051a140c'
down_revision = 'aa4c54cbfe21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
