"""Models Created

Revision ID: 8d030df6fff0
Revises: 88ae051a140c
Create Date: 2021-04-12 16:51:44.523436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d030df6fff0'
down_revision = '88ae051a140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
