"""empty message

Revision ID: a1fdc1324788
Revises: f8d3734cb97e
Create Date: 2021-03-23 08:52:00.829800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fdc1324788'
down_revision = 'f8d3734cb97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
