"""models updated

Revision ID: ba9bb467974c
Revises: 04244b935b00
Create Date: 2021-04-15 07:34:54.214685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9bb467974c'
down_revision = '04244b935b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=False))
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_teacher')
    op.drop_column('user', 'auth_provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_provider', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_teacher', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
