"""Models Created

Revision ID: e0e327c1918d
Revises: 7a6ed04886ad
Create Date: 2021-04-13 08:00:01.210878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e327c1918d'
down_revision = '7a6ed04886ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_enrolled_course_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'enrolled_course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enrolled_course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_enrolled_course_id_fkey', 'user', 'course', ['enrolled_course_id'], ['id'])
    # ### end Alembic commands ###
