"""Models Created

Revision ID: eb7068eb174f
Revises: 2664a34d3eba
Create Date: 2021-04-13 08:58:07.719979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb7068eb174f"
down_revision = "2664a34d3eba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
