"""models updated

Revision ID: ed52481355e8
Revises: 2b9e460b4b83
Create Date: 2021-04-13 09:02:33.416260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed52481355e8"
down_revision = "2b9e460b4b83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
