"""empty message

Revision ID: f8d3734cb97e
Revises: 3975b1ac80a3
Create Date: 2021-03-23 08:46:17.249210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d3734cb97e'
down_revision = '3975b1ac80a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
